default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: lalitha
  password: lalitha123

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: myapp_production
  url: <%= ENV['DATABASE_URL'] %>
